### ISSUE TITLE
What are the exact goals for this project?

### ISSUE THREAD

**Issue by robframpton** [jbalsas/iso-metal#1]
A few questions.

1. Are we hoping to remove the need for JSDom?
2. Are we hoping to create a set of tools that allow for server side rendering, or make metal.js compatible with isomorphic rendering right out of the box?

Obviously if we want to make metal.js isomorphic right out of the box, that answers question 1.

**Comment by jbalsas** [comment]
Hey @Robert-Frampton,

1. Yes
2. Make metal.js compatible with isomorphic rendering out of the box

This project is a simple sample of what should work. https://github.com/jbalsas/iso-metal/blob/master/index.js#L6-L14 explains exactly what shouldn't be needed to be able to do `node index.js`.

**Comment by jbalsas** [comment]
The goals of this project were masterfully achieved and released in https://github.com/metal/metal.js/blob/master/CHANGELOG.md#v2140-2017-11-02, so I'll proceed to close this and delete the repo!
